from __future__ import annotations


def schemas() -> list[dict]:
    return [
        {
            "type": "function",
            "name": "evaluate_trade_position",
            "description": "Assess economic state and vulnerabilities for a country.",
            "strict": True,
            "parameters": {
                "type": "object",
                "properties": {"country": {"type": "string"}},
                "required": ["country"],
                "additionalProperties": False,
            },
        },
        {
            "type": "function",
            "name": "calculate_tariff_impact",
            "description": "Model economic impact of imposing a tariff on a target good.",
            "strict": True,
            "parameters": {
                "type": "object",
                "properties": {
                    "country": {"type": "string"},
                    "target_good": {"type": "string"},
                    "rate": {"type": "number"},
                },
                "required": ["country", "target_good", "rate"],
                "additionalProperties": False,
            },
        },
        {
            "type": "function",
            "name": "propose_policy_action",
            "description": "Generate a structured policy action proposal.",
            "strict": True,
            "parameters": {
                "type": "object",
                "properties": {
                    "action_type": {"type": "string"},
                    "parameters": {"type": "object"},
                },
                "required": ["action_type", "parameters"],
                "additionalProperties": False,
            },
        },
        {
            "type": "function",
            "name": "assess_retaliation_risk",
            "description": "Estimate retaliation risk for a proposed action.",
            "strict": True,
            "parameters": {
                "type": "object",
                "properties": {"rate": {"type": "number"}},
                "required": ["rate"],
                "additionalProperties": False,
            },
        },
        {
            "type": "function",
            "name": "monitor_trade_flows",
            "description": "Track bilateral trade flow metrics.",
            "strict": True,
            "parameters": {
                "type": "object",
                "properties": {"country_pair": {"type": "array", "items": {"type": "string"}}},
                "required": ["country_pair"],
                "additionalProperties": False,
            },
        },
        {
            "type": "function",
            "name": "detect_policy_changes",
            "description": "Identify policy change events in recent history.",
            "strict": True,
            "parameters": {"type": "object", "properties": {}, "additionalProperties": False},
        },
        {
            "type": "function",
            "name": "analyze_supply_chains",
            "description": "Analyze supply chain stress for a sector.",
            "strict": True,
            "parameters": {
                "type": "object",
                "properties": {"sector": {"type": "string"}},
                "required": ["sector"],
                "additionalProperties": False,
            },
        },
        {
            "type": "function",
            "name": "predict_market_impact",
            "description": "Forecast market impact from a policy.",
            "strict": True,
            "parameters": {
                "type": "object",
                "properties": {"policy": {"type": "object"}},
                "required": ["policy"],
                "additionalProperties": False,
            },
        },
        {
            "type": "function",
            "name": "model_game_structure",
            "description": "Classify the current game structure.",
            "strict": True,
            "parameters": {
                "type": "object",
                "properties": {"scenario": {"type": "string"}},
                "required": ["scenario"],
                "additionalProperties": False,
            },
        },
        {
            "type": "function",
            "name": "find_nash_equilibrium",
            "description": "Solve for Nash equilibrium given players and strategies.",
            "strict": True,
            "parameters": {
                "type": "object",
                "properties": {
                    "players": {"type": "array", "items": {"type": "string"}},
                    "strategies": {"type": "object"},
                },
                "required": ["players", "strategies"],
                "additionalProperties": False,
            },
        },
        {
            "type": "function",
            "name": "predict_response",
            "description": "Predict opponent response to a given action.",
            "strict": True,
            "parameters": {
                "type": "object",
                "properties": {"action": {"type": "string"}, "opponent": {"type": "string"}},
                "required": ["action", "opponent"],
                "additionalProperties": False,
            },
        },
        {
            "type": "function",
            "name": "calculate_payoff_matrix",
            "description": "Calculate payoff matrix for the current scenario.",
            "strict": True,
            "parameters": {"type": "object", "properties": {}, "additionalProperties": False},
        },
        {
            "type": "function",
            "name": "detect_negotiation_window",
            "description": "Detect if a negotiation window is open based on welfare.",
            "strict": True,
            "parameters": {
                "type": "object",
                "properties": {"welfare_losses": {"type": "object"}},
                "required": ["welfare_losses"],
                "additionalProperties": False,
            },
        },
        {
            "type": "function",
            "name": "generate_deal_proposal",
            "description": "Generate a structured deal proposal.",
            "strict": True,
            "parameters": {
                "type": "object",
                "properties": {
                    "countries": {"type": "array", "items": {"type": "string"}},
                    "issues": {"type": "array", "items": {"type": "string"}},
                },
                "required": ["countries", "issues"],
                "additionalProperties": False,
            },
        },
        {
            "type": "function",
            "name": "evaluate_concession_value",
            "description": "Evaluate the value and risk of a concession offer.",
            "strict": True,
            "parameters": {
                "type": "object",
                "properties": {"offer": {"type": "object"}},
                "required": ["offer"],
                "additionalProperties": False,
            },
        },
        {
            "type": "function",
            "name": "manage_bargaining_round",
            "description": "Manage multi-round bargaining with current offers.",
            "strict": True,
            "parameters": {
                "type": "object",
                "properties": {"offers": {"type": "array", "items": {"type": "object"}}},
                "required": ["offers"],
                "additionalProperties": False,
            },
        },
        {
            "type": "function",
            "name": "execute_simulation_round",
            "description": "Execute a simulation round and update world state.",
            "strict": True,
            "parameters": {"type": "object", "properties": {}, "additionalProperties": False},
        },
        {
            "type": "function",
            "name": "generate_welfare_report",
            "description": "Generate welfare report for countries.",
            "strict": True,
            "parameters": {
                "type": "object",
                "properties": {"countries": {"type": "object"}},
                "required": ["countries"],
                "additionalProperties": False,
            },
        },
        {
            "type": "function",
            "name": "detect_equilibrium",
            "description": "Detect equilibrium in welfare outcomes.",
            "strict": True,
            "parameters": {
                "type": "object",
                "properties": {"state": {"type": "object"}},
                "required": ["state"],
                "additionalProperties": False,
            },
        },
        {
            "type": "function",
            "name": "trigger_event",
            "description": "Trigger a simulation event or shock.",
            "strict": True,
            "parameters": {
                "type": "object",
                "properties": {"event_type": {"type": "string"}},
                "required": ["event_type"],
                "additionalProperties": False,
            },
        },
    ]
